Component({
  mixins: [],
  data: {},
  props: {     
    onekitClass:"",    
     onekitStyle:"",     
     onekitId:"", 
     type:"",
     disabled:false,
     form:"",
     autofocus:"",
      disabled:"",
      form:"",
      formaction:"",
      formenctype:"",
      formmethod:"",
      formnovalidate:"",
      formtarget:"",
      name:"",
      type:"",
      value:"",
  },
});